/*
 * frmCalendario.java
 *
 * Created on 26 de diciembre de 2006, 10:36 PM
 */

package com.gmail.lrchfox3.formularios;

/**
 *
 * @author  Luis
 */
// <editor-fold defaultstate="collapsed" desc=" Librerias ">
import java.util.Date;
import com.gmail.lrchfox3.utilitarios.calendario.JCalendar;
// </editor-fold>

public class FrmCalendario extends javax.swing.JDialog {
    
    
    /** Creates new form frmCalendario */
    public FrmCalendario(java.awt.Frame parent, boolean modal) {
        //frmCalendario(parent, modal, null);
    }
    
    public FrmCalendario(java.awt.Frame parent, boolean modal, com.gmail.lrchfox3.utilitarios.calendario.JTextFieldDateEditor textoFecha) {
        super(parent, modal);
        initComponents();
        jcalendar = new JCalendar();
        jPanel1.add(jcalendar);	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calendario");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClicked(evt);
            }
        });
        jPanel2.add(btnSeleccionar, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(237, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClicked
        setFecha( jcalendar.getDate());
        dispose();
    }//GEN-LAST:event_btnSeleccionarClicked
    
    /**
     * @author: Chinchilla 29/12/2006
     */
    public Date getFecha(){
        return fecha; 
    }
    
    /**
     * @author: Chinchilla 29/12/2006
     */
    public void setFecha( Date f ) {
        fecha = f;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    public Date fecha;
    private JCalendar jcalendar;
}
