/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewController;


import ViewController.beans.ClaseJpaController;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author lchinchilla
 */
public class Clases extends javax.swing.JFrame {

    /**
     * Creates new form Clases
     */
    public Clases() {
        initComponents();  
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ControlClasesPU").createEntityManager();
        ClaseJpaController claseController = new ClaseJpaController(javax.persistence.Persistence.createEntityManagerFactory("ControlClasesPU"));
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : claseController.findClaseEntities();
        ControlClasesPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ControlClasesPU").createEntityManager();
        claseQuery = java.beans.Beans.isDesignTime() ? null : ControlClasesPUEntityManager.createQuery("SELECT c FROM Clase c");
        claseList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : claseQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClases = new com.gmail.lrchfox3.controles.tablas.JTablaBase();
        jTextoBase1 = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        jBotonAgregar1 = new com.gmail.lrchfox3.controles.botones.JBotonAgregar();
        jBotonEditar1 = new com.gmail.lrchfox3.controles.botones.JBotonEditar();
        jBotonEliminar1 = new com.gmail.lrchfox3.controles.botones.JBotonEliminar();
        jPanelInformacion1 = new com.gmail.lrchfox3.controles.paneles.JPanelInformacion();
        jEtiquetaBase1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jEtiquetaBase2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jEtiquetaBase3 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jTextoBase2 = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        jTextoBase3 = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        jScrollPane2 = new javax.swing.JScrollPane();
        jComentarioBase1 = new com.gmail.lrchfox3.controles.textos.JComentarioBase();
        btnImportarClases = new com.gmail.lrchfox3.controles.botones.JBotonImportar();
        btnExportarClase = new com.gmail.lrchfox3.controles.botones.JBotonExportar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ViewController/Resources/application"); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CLASES"))); // NOI18N

        tblClases.setName(bundle.getString("CLASES")); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, claseList, tblClases, "");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${referencia}"));
        columnBinding.setColumnName("Referencia");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nombreClase}"));
        columnBinding.setColumnName("Nombre Clase");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${comentario}"));
        columnBinding.setColumnName("Comentario");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblClases);

        int[] cols = new int[]{1,2};
        tblClases.setZoomCelda(cols);
        jPanelInformacion1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DETALLE"))); // NOI18N

        jEtiquetaBase1.setText(bundle.getString("REFERENCIA")); // NOI18N

        jEtiquetaBase2.setText(bundle.getString("CLASE")); // NOI18N

        jEtiquetaBase3.setText(bundle.getString("COMENTARIO")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblClases, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.referencia}"), jTextoBase2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblClases, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nombreClase}"), jTextoBase3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jComentarioBase1.setColumns(20);
        jComentarioBase1.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblClases, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.comentario}"), jComentarioBase1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(jComentarioBase1);

        javax.swing.GroupLayout jPanelInformacion1Layout = new javax.swing.GroupLayout(jPanelInformacion1);
        jPanelInformacion1.setLayout(jPanelInformacion1Layout);
        jPanelInformacion1Layout.setHorizontalGroup(
            jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInformacion1Layout.createSequentialGroup()
                        .addGroup(jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEtiquetaBase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEtiquetaBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextoBase3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanelInformacion1Layout.createSequentialGroup()
                        .addComponent(jEtiquetaBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextoBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanelInformacion1Layout.setVerticalGroup(
            jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacion1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEtiquetaBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextoBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEtiquetaBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextoBase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformacion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEtiquetaBase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnImportarClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarClasesActionPerformed(evt);
            }
        });

        btnExportarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextoBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImportarClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportarClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBotonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBotonEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelInformacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextoBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImportarClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExportarClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarClasesActionPerformed
        try {
            tblClases.importarExcelTabla();        
        } catch (Exception ex) {
            Logger.getLogger(Clases.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImportarClasesActionPerformed

    private void btnExportarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarClaseActionPerformed
        //Icon defaultIcon = btnExportarClase.getIcon();
        try {                
          //  btnExportarClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewController/imagenes/loading.gif"))); 
            //this.repaint();
            boolean retValue = tblClases.exportarTablaExcel();//this, btnExportarClase);        // TODO add your handling code here:
            /*if (retValue){
                btnExportarClase.setIcon(defaultIcon);
            }               */                         
        } catch (Exception ex) {
            //btnExportarClase.setIcon(defaultIcon);
            Logger.getLogger(Clases.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_btnExportarClaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clases().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager ControlClasesPUEntityManager;
    private com.gmail.lrchfox3.controles.botones.JBotonExportar btnExportarClase;
    private com.gmail.lrchfox3.controles.botones.JBotonImportar btnImportarClases;
    private java.util.List<model.entity.Clase> claseList;
    private javax.persistence.Query claseQuery;
    private javax.persistence.EntityManager entityManager;
    private com.gmail.lrchfox3.controles.botones.JBotonAgregar jBotonAgregar1;
    private com.gmail.lrchfox3.controles.botones.JBotonEditar jBotonEditar1;
    private com.gmail.lrchfox3.controles.botones.JBotonEliminar jBotonEliminar1;
    private com.gmail.lrchfox3.controles.textos.JComentarioBase jComentarioBase1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase jEtiquetaBase3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.gmail.lrchfox3.controles.paneles.JPanelInformacion jPanelInformacion1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.gmail.lrchfox3.controles.textos.JTextoBase jTextoBase1;
    private com.gmail.lrchfox3.controles.textos.JTextoBase jTextoBase2;
    private com.gmail.lrchfox3.controles.textos.JTextoBase jTextoBase3;
    private java.util.List list;
    private com.gmail.lrchfox3.controles.tablas.JTablaBase tblClases;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
