/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewMDIApplication.java
 *
 * Created on 09-23-2010, 06:17:23 PM
 */
package ViewController;

import ViewController.catalogos.CatalogosBase;
import com.gmail.lrchfox3.utilitarios.Utileria;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DTO.Carrera;
import model.DTO.Clase;
import model.DTO.Periodo;

/**
 *
 * @author chinchillal
 */
public class FormularioMaestro extends javax.swing.JFrame {

    /** Creates new form NewMDIApplication */
    public FormularioMaestro() {
        try {
            Utileria.lookAndFeelSystem(); //"Nimbus"
        } catch (Exception ex) {
            Logger.getLogger(FormularioMaestro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        initComponents();
    }

    public FormularioMaestro(String mensaje) {
        try {
            Utileria.lookAndFeelSystem(); //"Nimbus"
            if (mensaje.length() <= 0) {
                initComponents();
            } else {
                JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormularioMaestro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuItemEstudiantes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuItemGrupos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        mnuItemPeriodo = new javax.swing.JMenuItem();
        mnuItemClases = new javax.swing.JMenuItem();
        mnuItemCarrera = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de Clases");
        setExtendedState(6);

        fileMenu.setMnemonic('O');
        fileMenu.setText("Opciones");

        mnuItemEstudiantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuItemEstudiantes.setText("Estudiantes");
        mnuItemEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEstudiantesActionPerformed(evt);
            }
        });
        fileMenu.add(mnuItemEstudiantes);

        jMenu1.setText("Grupo: ");

        mnuItemGrupos.setText("Grupos");
        jMenu1.add(mnuItemGrupos);

        fileMenu.add(jMenu1);
        fileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Catalogos");

        mnuItemPeriodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuItemPeriodo.setText("Períodos");
        mnuItemPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPeriodoActionPerformed(evt);
            }
        });
        editMenu.add(mnuItemPeriodo);

        mnuItemClases.setText("Clases");
        mnuItemClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemClasesActionPerformed(evt);
            }
        });
        editMenu.add(mnuItemClases);

        mnuItemCarrera.setText("Carrera");
        mnuItemCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCarreraActionPerformed(evt);
            }
        });
        editMenu.add(mnuItemCarrera);

        menuBar.add(editMenu);

        helpMenu.setText("Ayuda");

        contentMenuItem.setText("Contenido");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(408, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuItemEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEstudiantesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Estudiantes estudiante = new Estudiantes();
                desktopPane.add(estudiante);
                estudiante.show();
            }
        });
    }//GEN-LAST:event_mnuItemEstudiantesActionPerformed

    private void mnuItemPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPeriodoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Periodo dto = new Periodo();
                model.BC.PeriodoBC dtoBC = new model.BC.PeriodoBC();

                CatalogosBase catalogosBase = new CatalogosBase(dto, dtoBC);
                desktopPane.add(catalogosBase);
                catalogosBase.show();
            }
        });
    }//GEN-LAST:event_mnuItemPeriodoActionPerformed

    private void mnuItemClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemClasesActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Clase dto = new Clase();
                model.BC.ClaseBC dtoBC = new model.BC.ClaseBC();

                CatalogosBase catalogosBase = new CatalogosBase(dto, dtoBC);
                desktopPane.add(catalogosBase);
                catalogosBase.show();
            }
        });
    }//GEN-LAST:event_mnuItemClasesActionPerformed

    private void mnuItemCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCarreraActionPerformed
               java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Carrera dto = new Carrera();
                model.BC.CarreraBC dtoBC = new model.BC.CarreraBC();

                CatalogosBase catalogosBase = new CatalogosBase(dto, dtoBC);
                desktopPane.add(catalogosBase);
                catalogosBase.show();
            }
        });
    }//GEN-LAST:event_mnuItemCarreraActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

    public void run() {
    new FormularioMaestro().setVisible(true);

    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuItemCarrera;
    private javax.swing.JMenuItem mnuItemClases;
    private javax.swing.JMenuItem mnuItemEstudiantes;
    private javax.swing.JMenuItem mnuItemGrupos;
    private javax.swing.JMenuItem mnuItemPeriodo;
    // End of variables declaration//GEN-END:variables
}
