/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.outlook.ludwen;

import static com.gmail.lrchfox3.utilitarios.Utileria.getFechaActual;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author LuisR
 */
public class CierreDiario extends javax.swing.JFrame {

    /**
     * Creates new form CierreDiario
     */
    public CierreDiario() {
        inicializar();
    }

    private void inicializar() {
        initComponents();
        this.dtFechaCierre.setVisible(false);
        this.dtFechaCierre.setDate(getFechaActual());

        txtCantidad2.setNextFocusableComponent(txtCantidad1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popCaja = new javax.swing.JPopupMenu();
        mnuLimpiar = new javax.swing.JMenuItem();
        pnlCaja = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lblCantidadBilletes = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl500 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl100 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl50 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl20 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl10 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl5 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lbl1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMontoApertura = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        txtCantidad500 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad100 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad50 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad20 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad10 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad5 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad2 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtCantidad1 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        txtMontoMonedas = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblMontoTotalCaja = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        lblMonto50 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto500 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto5 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto100 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto10 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto20 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonto1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblApertura = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblTotalCaja = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMonedas = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        btnEditarFechaCierre = new com.gmail.lrchfox3.controles.botones.paint.JBotonLapiz();
        lblFechaCierre = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        lblFecha = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        dtFechaCierre = new com.gmail.lrchfox3.utilitarios.calendario.JDateChooser();
        lblApertura1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        lblMontoApertura2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        jPanelConTitulo1 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        jEtiquetaTitulo1 = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        jTextoScrollBase1 = new com.gmail.lrchfox3.controles.textos.JTextoScrollBase();
        txtCantidad501 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        jPanelConTitulo2 = new com.gmail.lrchfox3.controles.paneles.JPanelConTitulo();
        lbl501 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        txtCantidad502 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lbl503 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        txtCantidad503 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lbl502 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jBotonAceptar1 = new com.gmail.lrchfox3.controles.botones.JBotonAceptar();
        jTextoBase1 = new com.gmail.lrchfox3.controles.textos.JTextoBase();
        lbl504 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        lbl505 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        txtCantidad504 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();
        lblApertura2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaBase();
        jEtiquetaTitulo2 = new com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo();
        txtCantidad505 = new com.gmail.lrchfox3.controles.textos.JTextoFormato();

        mnuLimpiar.setLabel("Limpiar");
        mnuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLimpiarActionPerformed(evt);
            }
        });
        popCaja.add(mnuLimpiar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cierre Diario");
        setExtendedState(2);
        setResizable(false);
        setState(1);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlCaja.setComponentPopupMenu(popCaja);
        pnlCaja.setTitulo("Caja");

        lblCantidadBilletes.setText("Cantidad de Billetes:");
        lblCantidadBilletes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl500.setLabelFor(txtCantidad500);
        lbl500.setText("500 x");
        lbl500.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl100.setLabelFor(txtCantidad100);
        lbl100.setText("100 x");
        lbl100.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl50.setLabelFor(txtCantidad50);
        lbl50.setText("50 x");
        lbl50.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl20.setLabelFor(txtCantidad20);
        lbl20.setText("20 x");
        lbl20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl10.setLabelFor(txtCantidad10);
        lbl10.setText("10 x");
        lbl10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl5.setLabelFor(txtCantidad5);
        lbl5.setText("5 x");
        lbl5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl2.setLabelFor(txtCantidad2);
        lbl2.setText("2 x");
        lbl2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lbl1.setLabelFor(txtCantidad1);
        lbl1.setText("1 x");
        lbl1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMontoApertura.setText("Lps");

        txtCantidad500.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad500.setComas(false);
        txtCantidad500.setExpresionRegular("\\d*");
        txtCantidad500.setMaxCaracteres(3);
        txtCantidad500.setNextFocusableComponent(txtCantidad100);
        txtCantidad500.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad500FocusLost(evt);
            }
        });
        txtCantidad500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad500KeyReleased(evt);
            }
        });

        txtCantidad100.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad100.setNextFocusableComponent(txtCantidad50);
        txtCantidad100.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad100FocusLost(evt);
            }
        });
        txtCantidad100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad100KeyReleased(evt);
            }
        });

        txtCantidad50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad50.setNextFocusableComponent(txtCantidad20);
        txtCantidad50.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad50FocusLost(evt);
            }
        });
        txtCantidad50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad50KeyReleased(evt);
            }
        });

        txtCantidad20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad20.setNextFocusableComponent(txtCantidad10);
        txtCantidad20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad20FocusLost(evt);
            }
        });
        txtCantidad20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad20KeyReleased(evt);
            }
        });

        txtCantidad10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad10.setNextFocusableComponent(txtCantidad5);
        txtCantidad10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad10FocusLost(evt);
            }
        });
        txtCantidad10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad10KeyReleased(evt);
            }
        });

        txtCantidad5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad5.setNextFocusableComponent(txtCantidad2);
        txtCantidad5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad5FocusLost(evt);
            }
        });
        txtCantidad5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad5KeyReleased(evt);
            }
        });

        txtCantidad2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad2.setNextFocusableComponent(txtCantidad1);
        txtCantidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad2FocusLost(evt);
            }
        });
        txtCantidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad2KeyReleased(evt);
            }
        });

        txtCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad1.setNextFocusableComponent(txtMontoMonedas);
        txtCantidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad1FocusLost(evt);
            }
        });
        txtCantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad1KeyReleased(evt);
            }
        });

        txtMontoMonedas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoMonedas.setExpresionRegular("[0-9]+(\\.[0-9][0-9]?)?");
        txtMontoMonedas.setMaxCaracteres(8);

        lblMontoTotalCaja.setText("Lps");

        lblMonto50.setText("=");
        lblMonto50.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto500.setText("= ");
        lblMonto500.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto5.setText("=");
        lblMonto5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto100.setText("=");
        lblMonto100.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto10.setText("=");
        lblMonto10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto2.setText("=");
        lblMonto2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto20.setText("=");
        lblMonto20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblMonto1.setText("=");
        lblMonto1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblApertura.setText("Apertura");
        lblApertura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblTotalCaja.setText("Total");
        lblTotalCaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblMonedas.setLabelFor(txtMontoMonedas);
        lblMonedas.setText("Monedas");
        lblMonedas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnEditarFechaCierre.setToolTipText("Lápiz");
        btnEditarFechaCierre.setNextFocusableComponent(txtCantidad500);
        btnEditarFechaCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFechaCierreActionPerformed(evt);
            }
        });

        lblFechaCierre.setText("25/02/2015");

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setLabelFor(lblFechaCierre);
        lblFecha.setText("Fecha");
        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dtFechaCierre.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        lblApertura1.setText("Total Caja - Caja Apertura");
        lblApertura1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblMontoApertura2.setText("Lps");

        javax.swing.GroupLayout pnlCajaLayout = new javax.swing.GroupLayout(pnlCaja);
        pnlCaja.setLayout(pnlCajaLayout);
        pnlCajaLayout.setHorizontalGroup(
            pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCajaLayout.createSequentialGroup()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addComponent(txtCantidad20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonto20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addComponent(txtCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonto5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCantidadBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajaLayout.createSequentialGroup()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMontoMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonto500, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto50, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMontoTotalCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(pnlCajaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMontoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtCantidad100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMonto100, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(pnlCajaLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dtFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblApertura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMontoApertura2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlCajaLayout.setVerticalGroup(
            pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCajaLayout.createSequentialGroup()
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMontoApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEditarFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(dtFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidadBilletes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMonto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCantidad100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMonto100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMontoTotalCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCajaLayout.createSequentialGroup()
                        .addComponent(lblApertura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(lblMontoApertura2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelConTitulo1.setTitulo("Facturado");

        jEtiquetaTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEtiquetaTitulo1.setText("Lps");

        txtCantidad501.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad501.setComas(false);
        txtCantidad501.setNextFocusableComponent(txtCantidad100);
        txtCantidad501.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad501FocusLost(evt);
            }
        });
        txtCantidad501.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad501KeyReleased(evt);
            }
        });
        jTextoScrollBase1.setViewportView(txtCantidad501);

        javax.swing.GroupLayout jPanelConTitulo1Layout = new javax.swing.GroupLayout(jPanelConTitulo1);
        jPanelConTitulo1.setLayout(jPanelConTitulo1Layout);
        jPanelConTitulo1Layout.setHorizontalGroup(
            jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextoScrollBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jEtiquetaTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelConTitulo1Layout.setVerticalGroup(
            jPanelConTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo1Layout.createSequentialGroup()
                .addComponent(jTextoScrollBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEtiquetaTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelConTitulo2.setTitulo("Cierre");

        lbl501.setLabelFor(txtCantidad500);
        lbl501.setText("Continental");
        lbl501.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtCantidad502.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad502.setComas(false);
        txtCantidad502.setExpresionRegular("\\d*");
        txtCantidad502.setMaxCaracteres(3);
        txtCantidad502.setNextFocusableComponent(txtCantidad100);
        txtCantidad502.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad502FocusLost(evt);
            }
        });
        txtCantidad502.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad502KeyReleased(evt);
            }
        });

        lbl503.setLabelFor(txtCantidad500);
        lbl503.setText("Justificación");
        lbl503.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtCantidad503.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad503.setComas(false);
        txtCantidad503.setExpresionRegular("\\d*");
        txtCantidad503.setMaxCaracteres(3);
        txtCantidad503.setNextFocusableComponent(txtCantidad100);
        txtCantidad503.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad503FocusLost(evt);
            }
        });
        txtCantidad503.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad503KeyReleased(evt);
            }
        });

        lbl502.setLabelFor(txtCantidad500);
        lbl502.setText("Atlantida");
        lbl502.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jTextoBase1.setEditable(false);

        lbl504.setLabelFor(txtCantidad500);
        lbl504.setText("Diferencia");
        lbl504.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jScrollPane1.setViewportView(jTextPane1);

        lbl505.setLabelFor(txtCantidad500);
        lbl505.setText("Deposito Banco");
        lbl505.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtCantidad504.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad504.setComas(false);
        txtCantidad504.setExpresionRegular("\\d*");
        txtCantidad504.setMaxCaracteres(3);
        txtCantidad504.setNextFocusableComponent(txtCantidad100);
        txtCantidad504.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad504FocusLost(evt);
            }
        });
        txtCantidad504.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad504KeyReleased(evt);
            }
        });

        lblApertura2.setText("Caja");
        lblApertura2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jEtiquetaTitulo2.setText("Lps");

        txtCantidad505.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad505.setComas(false);
        txtCantidad505.setExpresionRegular("\\d*");
        txtCantidad505.setMaxCaracteres(3);
        txtCantidad505.setNextFocusableComponent(txtCantidad100);
        txtCantidad505.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidad505FocusLost(evt);
            }
        });
        txtCantidad505.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidad505KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelConTitulo2Layout = new javax.swing.GroupLayout(jPanelConTitulo2);
        jPanelConTitulo2.setLayout(jPanelConTitulo2Layout);
        jPanelConTitulo2Layout.setHorizontalGroup(
            jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl505, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl503, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl501, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidad504, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantidad502, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl504, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl502, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextoBase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantidad503, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblApertura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEtiquetaTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotonAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConTitulo2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad505, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(357, 357, 357)))
                .addContainerGap())
        );
        jPanelConTitulo2Layout.setVerticalGroup(
            jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl501, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad502, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl502, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad503, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextoBase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl504, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl505, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad504, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConTitulo2Layout.createSequentialGroup()
                        .addComponent(lbl503, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad505, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotonAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelConTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jEtiquetaTitulo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblApertura2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelConTitulo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(jPanelConTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(pnlCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelConTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(492, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarFechaCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFechaCierreActionPerformed

        if (this.dtFechaCierre.isVisible()) {
            SimpleDateFormat sdfDate = new SimpleDateFormat("dd/MM/yyyy");
            this.lblFechaCierre.setText(sdfDate.format(this.dtFechaCierre.getDate()));
            this.lblFechaCierre.setVisible(true);
            this.dtFechaCierre.setVisible(false);
        } else {
            this.lblFechaCierre.setVisible(false);
            this.dtFechaCierre.setVisible(true);
        }

    }//GEN-LAST:event_btnEditarFechaCierreActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtCantidad500.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtCantidad500FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad500FocusLost
        if (this.txtCantidad500.getText().length() > 0) {
            double cantidad = 500 * Double.parseDouble(this.txtCantidad500.getText());
            this.lblMonto500.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad500FocusLost

    private void txtCantidad100FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad100FocusLost
        if (this.txtCantidad100.getText().length() > 0) {
            double cantidad = 100 * Double.parseDouble(this.txtCantidad100.getText());
            this.lblMonto100.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
    }//GEN-LAST:event_txtCantidad100FocusLost

    private void txtCantidad50FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad50FocusLost
        if (this.txtCantidad50.getText().length() > 0) {
            double cantidad = 50 * Double.parseDouble(this.txtCantidad50.getText());
            this.lblMonto50.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad50FocusLost

    private void txtCantidad20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad20FocusLost
        if (this.txtCantidad20.getText().length() > 0) {
            double cantidad = 20 * Double.parseDouble(this.txtCantidad20.getText());
            this.lblMonto20.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
    }//GEN-LAST:event_txtCantidad20FocusLost

    private void txtCantidad10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad10FocusLost
        if (this.txtCantidad10.getText().length() > 0) {
            double cantidad = 10 * Double.parseDouble(this.txtCantidad10.getText());
            this.lblMonto10.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
    }//GEN-LAST:event_txtCantidad10FocusLost

    private void txtCantidad5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad5FocusLost
        if (this.txtCantidad5.getText().length() > 0) {
            double cantidad = 5 * Double.parseDouble(this.txtCantidad5.getText());
            this.lblMonto5.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
    }//GEN-LAST:event_txtCantidad5FocusLost

    private void txtCantidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad2FocusLost
        if (this.txtCantidad2.getText().length() > 0) {
            double cantidad = 2 * Double.parseDouble(this.txtCantidad2.getText());
            this.lblMonto2.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
    }//GEN-LAST:event_txtCantidad2FocusLost

    private void txtCantidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad1FocusLost
        if (this.txtCantidad1.getText().length() > 0) {
            double cantidad = 1 * Double.parseDouble(this.txtCantidad1.getText());
            this.lblMonto1.setText("= Lps " + df2.format(cantidad));
            totalCaja();
        }
    }//GEN-LAST:event_txtCantidad1FocusLost

    private void txtCantidad500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad500KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad100.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad500KeyReleased

    private void txtCantidad100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad100KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad50.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad100KeyReleased

    private void txtCantidad50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad50KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad20.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad50KeyReleased

    private void txtCantidad20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad20KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad10.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad20KeyReleased

    private void txtCantidad10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad10KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad5.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad10KeyReleased

    private void txtCantidad5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad5KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad2.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad5KeyReleased

    private void txtCantidad2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtCantidad1.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad2KeyReleased

    private void txtCantidad1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtMontoMonedas.requestFocus();
        }
    }//GEN-LAST:event_txtCantidad1KeyReleased

    private void mnuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLimpiarActionPerformed
        this.txtCantidad500.setText("");
        this.txtCantidad100.setText("");
        this.txtCantidad50.setText("");
        this.txtCantidad20.setText("");
        this.txtCantidad10.setText("");
        this.txtCantidad5.setText("");
        this.txtCantidad2.setText("");
        this.txtCantidad1.setText("");
        this.txtMontoMonedas.setText("");
        this.lblMonto500.setText("=");
        this.lblMonto100.setText("=");
        this.lblMonto50.setText("=");
        this.lblMonto20.setText("=");
        this.lblMonto10.setText("=");
        this.lblMonto5.setText("=");
        this.lblMonto2.setText("=");
        this.lblMonto1.setText("=");                     
        this.lblMontoTotalCaja.setText("Lps");
        this.txtCantidad500.requestFocus();
    }//GEN-LAST:event_mnuLimpiarActionPerformed

    private void txtCantidad502FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad502FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad502FocusLost

    private void txtCantidad502KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad502KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad502KeyReleased

    private void txtCantidad503FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad503FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad503FocusLost

    private void txtCantidad503KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad503KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad503KeyReleased

    private void txtCantidad504FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad504FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad504FocusLost

    private void txtCantidad504KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad504KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad504KeyReleased

    private void txtCantidad505FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad505FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad505FocusLost

    private void txtCantidad505KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad505KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad505KeyReleased

    private void txtCantidad501KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad501KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad501KeyReleased

    private void txtCantidad501FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidad501FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad501FocusLost

    private void totalCaja() {
        double c500 = 500 * Double.parseDouble((this.txtCantidad500.getText().length() <= 0 ? "0" : this.txtCantidad500.getText()));
        double c100 = 100 * Double.parseDouble((this.txtCantidad100.getText().length() <= 0 ? "0" : this.txtCantidad100.getText()));
        double c50 = 50 * Double.parseDouble((this.txtCantidad50.getText().length() <= 0 ? "0" : this.txtCantidad50.getText()));
        double c20 = 20 * Double.parseDouble((this.txtCantidad20.getText().length() <= 0 ? "0" : this.txtCantidad20.getText()));
        double c10 = 10 * Double.parseDouble((this.txtCantidad10.getText().length() <= 0 ? "0" : this.txtCantidad10.getText()));
        double c5 = 5 * Double.parseDouble((this.txtCantidad5.getText().length() <= 0 ? "0" : this.txtCantidad5.getText()));
        double c2 = 2 * Double.parseDouble((this.txtCantidad2.getText().length() <= 0 ? "0" : this.txtCantidad2.getText()));
        double c1 = 1 * Double.parseDouble((this.txtCantidad1.getText().length() <= 0 ? "0" : this.txtCantidad1.getText()));
        this.lblMontoTotalCaja.setText("= Lps " + df2.format(c500 + c100 + c50 + c20 + c10 + c5 + c2 + c1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CierreDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CierreDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CierreDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CierreDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CierreDiario().setVisible(true);
            }
        });
    }

    DecimalFormat df2 = new DecimalFormat("#,###,###,##0.00");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gmail.lrchfox3.controles.botones.paint.JBotonLapiz btnEditarFechaCierre;
    private com.gmail.lrchfox3.utilitarios.calendario.JDateChooser dtFechaCierre;
    private com.gmail.lrchfox3.controles.botones.JBotonAceptar jBotonAceptar1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo jEtiquetaTitulo1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo jEtiquetaTitulo2;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo1;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo jPanelConTitulo2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private com.gmail.lrchfox3.controles.textos.JTextoBase jTextoBase1;
    private com.gmail.lrchfox3.controles.textos.JTextoScrollBase jTextoScrollBase1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl10;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl100;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl20;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl5;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl50;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl500;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl501;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl502;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl503;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl504;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lbl505;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblApertura;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblApertura1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblApertura2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblCantidadBilletes;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblFecha;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblFechaCierre;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonedas;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto1;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto10;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto100;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto20;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto5;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto50;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblMonto500;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblMontoApertura;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblMontoApertura2;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaTitulo lblMontoTotalCaja;
    private com.gmail.lrchfox3.controles.textos.JEtiquetaBase lblTotalCaja;
    private javax.swing.JMenuItem mnuLimpiar;
    private com.gmail.lrchfox3.controles.paneles.JPanelConTitulo pnlCaja;
    private javax.swing.JPopupMenu popCaja;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad1;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad10;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad100;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad2;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad20;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad5;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad50;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad500;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad501;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad502;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad503;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad504;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtCantidad505;
    private com.gmail.lrchfox3.controles.textos.JTextoFormato txtMontoMonedas;
    // End of variables declaration//GEN-END:variables
}
